	PRINT "Initializing USER.DAT";

	OPEN "R",#1,"USER.DAT",192
	FIELD #1,192 AS USER.DISK$

	LSET USER.DISK$=STRING$(LEN(USER.DISK$),0)

	FOR REC%=1 TO 96
		IF (REC% MOD 10)=0 THEN PRINT ".";
		PUT #1,REC%
	NEXT REC%

	CLOSE
	PRINT "Ok."
	END
